Le calcul différentiel
=====

Indexation et slicing
-----

Dans le dernier TP vous vous êtes familiarisé avec les vecteurs et tableaux numpy. Nous allons maintenant vous présenter une façon de manipuler ces objets de façon plus précise.

Supposons que nous avons le vecteur suivant

In [1]:
import numpy as np
vecteur = np.array([1,2,3,4,5,6])
print(vecteur)

[1 2 3 4 5 6]


et que nous voulons avoir accès au troisième élément. Nous pouvons alors utiliser la méthode suivante:

In [2]:
element3 = vecteur[2]
print(element3)

3


En effet, souvenez-vous qu'en python les indices commencent à 0. Le troisième élément se trouve donc à l'indice 2. Nous pouvons aussi utiliser cette syntaxe pour modifier un élément unique dans un vecteur:

In [3]:
vecteur[2] = -1
print(vecteur)

[ 1  2 -1  4  5  6]


C'est ce qu'on appelle l'indexation. On peut aussi utiliser des chiffres négatifs pour compter à partir de la fin. L'indice -1 est donc le dernier élément, l'indice -2 l'avant dernier et ainsi de suite.

In [4]:
print(vecteur[-1])

6


Une autre méthode encore plus puissante est le «slicing». Elle est appelée ainsi car elle permet d'obtenir une «tranche» du vecteur. Le «slicing» fonctionne ainsi:

In [5]:
debut = 1
fin = 4
pas = 2
print(vecteur[debut:fin:pas])

[2 4]


Ceci nous donne les éléments des indices «début» (inclusivement) à «fin» (exclusivement) par intervalle de «pas». Par défaut le pas est de 1. On peut donc omettre le pas si on n'en a pas besoin:

In [6]:
print(vecteur[3:5])

[4 5]


On peut aussi laisser le début et/ou la fin vide. Dans ce cas le début prend la valeur par défaut 0 et la fin la valeur -1

In [7]:
print(vecteur[:])

[ 1  2 -1  4  5  6]


Les mêmes principes s'appliquent pour un tableau en deux dimensions. Soit le tableau

In [8]:
tableau = np.array([[0,1,2,3,4,5,6,7,8,9],[10,11,12,13,14,15,16,17,18,19]])
print(tableau)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


Pour aller chercher l'élément 15 qui se trouve dans la sixième colonne de la deuxième rangé, on écrit simplement

In [9]:
print(tableau[1,5])

15


Et si on veut extraire la deuxième et la troisième colonne uniquement on peut faire

In [10]:
print(tableau[:,1:3])

[[ 1  2]
 [11 12]]


À votre tour
-----

En utilisant les principes du slicing, retenez uniquement les chiffres pairs du tableau.

Laboratoire
=====

Sympy et les équations différentielles
-----

Dans le dernier TP, vous avez utilisé sympy pour programmer l'équation d'un neurone de type intégration-et-tir parfait. Nous alons maintenant faire de même pour le modèle intégration-et-tir avec fuite. Ce modèle est défini comme suit:
$$C_m \frac{dV_m(t)}{dt}=I(t)-\frac{V_m(t)}{R_m}$$
Lorsque la tension de la membrane du neurone atteint un seuil $V_{th}$, le neurone «tire» et on remet la tension à zéro.

Votre première tâche est de programmer chaque côté de l'équation avec sympy. Vous devriez donc avoir deux équations. N'oubliez pas d'importer votre librairie avant de l'utiliser!

En utilisant les équations que vous venez de définir, et en supposant que le courant entrant $I(t)$ est constant et égal à $i$, trouvez l'équation qui permet de calculer le nombre de temps avant que le neurone tire en fonction des paramètres, c'est-à-dire le moment où $V_m(t)=V_{th}$.

Toujours en utilisant des équation symboliques et en supposant un courant entrant continu, trouvez l'équation qui permet de calculer le courant minimal $i_{th}$ pour que la membrane du neurone atteigne la tension critique $V_{th}$.

Trouvez maintenant la fonction par partie qui défini la fréquence de tir par rapport au courant entrant pour un neurone de type intégration-et-tir avec fuite lorsque le courant entrant est continu. Indice: la fonction sera égale à $0$ pour $i<i_{th}$

En utilisant numpy et matplotlib, dessinez la fonction que vous venez de définir . Vous devrez donner une valeur de votre choix aux parmètres $C_m$, $R_m$ et $V_{th}$. Expérimentez avec différentes valeurs de paramètres et voyez comment la fonction change!

La différentiation numérique
-----

Dans certains cas, il peut être très difficile et peu utile d'utiliser la différentiation symbolique. La différentiation numérique, bien qu'étant une approximation, est bien souvent suffisante lorsqu'on cherche simplement à expérimenter avec un système. Nous allons reprendre l'équation du neurone intégration-et-tir avec fuite et allons utiliser la définition de la dérivée pour trouver une approximation qui sera plus facile à calculer numériquement

La dérivée est définie ainsi:
$$\frac{df(x)}{dx}=\lim_{\Delta x\rightarrow 0}\frac{f(x+\Delta x)-f(x)}{\Delta x}$$
Par conséquent, si on prend $\Delta x$ assez petit, on peut généralement obtenir une assez bonne approximation avec l'équation
$$\frac{df(x)}{dx}\approx\frac{f(x+\Delta x)-f(x)}{\Delta x}$$

Dans beaucoup de cas lorsqu'on travaille avec des modèles de systèmes naturels, on fait face à des équations du type
$$\frac{df(x)}{dx}=g(x)$$
C'est d'ailleurs le cas pour notre modèle de neurone. Dans ces cas on peut utiliser la différentiation numérique pour transformer notre équation sous la forme
$$f(x+\Delta x)=f(x)+\Delta x \cdot g(x)$$
qui est généralement beaucoup plus facile à résoudre numériquement.

En utilisant la méthode que l'on vient de décrire, transformez l'équation symbolique du neurone intégration-et-tir en son approximation numérique. Écrivez une fonction python qui prend $V_m(t)$, $\Delta t$, $C_m$, $R_m$ et $V_{th}$ en paramètres et renvoie $V_m(t+\Delta t)$. N'oubliez pas que si $V_m$ dépasse $V_{th}$, la tension du neurone est remis à zéro.

Nous allons maintenant utiliser la dérivée numérique pour simuler un système de plusieurs neurones. L'état des neurones dans le temps va être enregistré dans un tableau numpy. Chaque ligne représente un neurone et chaque colone représente un indice de temps.

Commencez par définir les variables $n$ pour le nombre de neurones, $dt$ pour l'intervalle de temps entre chaque étape de l'intégration et $d$ pour la durée de l'expérience en secondes. Nous allons commencer avec les valeurs $n=10$, $dt=0.1$ et $d=100$. Initialisez ensuite un tableau numpy vide (c'est-à-dire avec la valeur zéro partout) de taille appropriée. Attention, ne calculez pas la bonne taille à la main. Vous devez utiliser les paramètres pour déterminer la taille afin que le code s'adapte par lui-même si vous décidez de modifier un paramètre.

Pour cette expérience, nous allons supposer que chaque neurone dans notre système est connecté à tous les autres avec une force aléatoire entre $0$ et $1$. Le courant entrant $I(t)$ sera la somme des tensions $V_m(t-dt)$ des autres neurones multiplié par leurs forces de connections respectives. Créez un tableau numpy de taille $n\times n$ avec des valeurs aléatoires entre $0$ et $1$ qui représentera les connections entre chaque paire de neurones.

Comme nous n'injectons pas de courant extérieur dans cette expérience, si les neurones commencent tous avec une tension nulle ils resteront ainsi. Il faut donc initialiser les neurones pour le premier indice de temps. Dans le tableau créé plus haut, assignez des valeurs aléatoires entre $0$ et $V_{th}$ à la première colone.

Nous avons maintenant tout ce qu'il faut pour exécuter notre expérience. En utilisant l'équation définie au début de cette section et le tableau de connections, générez le reste des valeurs du tableau de tensions en fonction du temps. Commencez en générant les valeurs de la deuxième colone à partir de celles de la première et progressez ainsi d'une colone à l'autre jusqu'à ce que vous ayez terminé de remplir le tableau.

En utilisant matplotlib, dessinez la tension de chaque neurone en fonction du temps. Pour ce faire, créez un tableau avec 10 graphiques superposés. Les graphiques devraient partager l'axe du temps mais avoir des axes de tension individuels.

Diminuez la valeur de $dt$ afin que l'approximation numérique soit assez proche de la réalité. Vous saurez que vous avez atteint la bonne valeur lorsque diminuer $dt$ ne modifie pas significativement l'apparence de votre graphique. Attention de ne pas recalculer les valeurs aléatoires sinon le graphique changera complètement!

Si vous le voulez, vous pouvez ensuite expérimenter avec les différents paramètres de la simulation. Que se passe-t-il si vous diminuez la force maximale de connection entre les neurones? Ou si vous réduisez la moitié des connections à 0? Est-ce que la tension initiale des neurones a un effet à long terme?